{% set version = "1.0.2" %}

package:
  name: sphinxcontrib-htmlhelp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinxcontrib-htmlhelp/sphinxcontrib-htmlhelp-{{ version }}.tar.gz
  sha256: 4670f99f8951bd78cd4ad2ab962f798f5618b17675c35c5ac3b2132a14ea8422

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  requires:
    # This is a circular dependency b/c sphinx depends on this package now :-/
    - sphinx >=2
  imports:
    - sphinxcontrib
    - sphinxcontrib.htmlhelp

about:
  home: http://sphinx-doc.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: sphinxcontrib-htmlhelp is a sphinx extension which ...

extra:
  recipe-maintainers:
    - ocefpaf
