travis:
  secure:
    BINSTAR_TOKEN: fBqDew2TZN2GPhuTB06JDjzYI1bIvCWbSExJYLYJv32KsYOnhaoUz8SBVvRpJ7tElgx4wp/z2LE0eIUFS8Y8oBY/c3fNzlbdNopIHmrD2+7/MGruaw25dhh+iwnqri1r5bdwF+zuiXr048rsAtyW4ZJ5JSLgCa/g85UnjqOjd3LmZ7fVgqWge0EqQ2JCes7g7Qj37EDXjO1fD3CmucNuSNfkrvOtJwabdMPiq/oBJwjTLlbMsgZ7Y1qWNwQ4Vvrrw/Rb9pOgY7TrYid4pvV5aAlh3oXVQTau3YrxuzUOZcy+4Y4h5xjLjZrNB+3wQoNgUs2zq0meLmIinQEEBvLxMUvtPkxK0800kZRs+igXsUzLCFKwnNdyhcQfPJTEaktr4kQtxydol45fGgRz1WTOpzZbbYH68TqO0jxixchvH7ZBDuk+6sEeGqiIeXrNZ8+LlHfyP2le5t/Vr9JbZaUzSLJ1PGqwKp3Rzzaq9OrUTP1WF3OEKc8kIY5QSnRSrMipe3gbs3j2HReWdYL8PBmj/z7qUfanuzpdq2YcRT4C1oKqyvyiv+1PMdPL3fQmjQLlVqRK6YsjLkreUclK8JO6EWXc4RAva4DWIF+TDARvrSYdoGx94hidN7s+wysjoTZv5kemB3544cA5YNqsM90x+t0eQDOOStXBgeK/Dx4mkkI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
